version: "3.9"

services:
  pgdb:
    image: postgres:9.5
    restart: always
    container_name: pgdb
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdb_di:/var/lib/postgresql/data9

  nginx:
    build:
      context: .
      target: nginx
    container_name: nginx
    volumes:
      - ./config-nginx.d:/etc/nginx/conf.d
      - staticfiles:/var/www/html/static
      - mediafiles:/var/www/html/media
    depends_on:
      - django
    links:
      - django
    ports:
      - "80:80"

  django:
    build:
      context: .
      target: django
    container_name: django
    command: gunicorn Messager.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
      - staticfiles:/app/static
      - mediafiles:/app/media
      - node_modules:/app/node
    depends_on:
      - pgdb

  npm:
    build:
      context: .
      target: npm
    volumes:
      - node_modules:/app/


volumes:
  pgdb_di: null
  staticfiles:
  mediafiles:
  node_modules: