version: "3.9"

services:
  pgdb:
    image: postgres:9.5
    restart: always
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdb_di:/var/lib/postgresql/data9

  npm:
    build:
      context: .
      target: npm
    volumes:
      - .:/app/

  django:
    build:
      context: .
      target: django
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - pgdb




volumes:
  pgdb_di: